language: node_js
cache: npm
notifications:
  email: false
env:
  - TEST=test
node_js:
  - lts/*
  - node
install: npm install
script:
  - npm run validate
branches:
  only:
    - master
    - next
    - beta

jobs:
  include:
    - stage: deploy
      if: branch = master AND type != pull_request
      node_js: lts/*
      env:
        - PRODUCTION=production
      script:
        - echo "Deploying to github pages ..."
        - npm run docz:build
      deploy:
        provider: pages
        local_dir: .docz/dist
        cleanup: false
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
