name: CI

on:
  push:
    branches: [master, beta, next, develop]
  pull_request:
    branches: [master, beta, next, develop]

jobs:
  test:
    name: Running tests...
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing
      - run: npm install
      - name: Test
      - run: npm run validate
